# Generated by Django 4.2.4 on 2023-08-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="is_acitve",
            field=models.BooleanField(default=False),
        ),
    ]
